# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
 - package-ecosystem: 'npm'
    directory: './packages/server'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    labels:
      - 'npm dependencies'
      - 'data-server'

  - package-ecosystem: 'npm'
    directory: './packages/frontend'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    labels:
      - 'npm dependencies'
      - 'frontend'

  - package-ecosystem: 'npm'
    directory: './packages/api/rest'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    labels:
      - 'npm dependencies'
      - 'api-rest'

  - package-ecosystem: 'npm'
    directory: './packages/api/ws'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    labels:
      - 'npm dependencies'
      - 'ws-rest'