name: Run linter

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare job
        working-directory: ./
        run: npm install

      - name: JS Linter
        working-directory: ./packages/frontend
        run: npm run lint
